### ISSUE TITLE
Conflict in autoloader naming.

### ISSUE THREAD

**Issue by leevigraham** [FabienPennequin/FPNTagBundle#3]
Repasted from: https://github.com/FabienPennequin/FPNTagBundle/issues/2#issuecomment-2729202

<hr />

This also fixed my issue but raises another one (I think).

I don't think the autoloader should use 'DoctrineExtensions' as the key. I'm also using @l3pp4rd's doctrine extensions [implemented in Symfony2](https://github.com/stof/StofDoctrineExtensionsBundle) by @stof.

I'm still feeling my way around Symfony2 so I can't offer a pull request or clearly identify the issue. Happy to be told that I'm wrong but isn't there a chance of naming conflicts when using 'DoctrineExtensions'?

**Comment by stof** [comment]
the issue should not been opened here. The bundle does not have any issue about namespace conflicts. The issue is with the related library.

And btw, you don't have any issue with @l3pp4rd's extensions as they don't use this namespace (the namespace is `Gedmo`). You would have some when using @beberlei's one though

**Comment by stof** [comment]
btw, reading your message again, I think you misunderstood what the autoloader config is. The autoloader does not choose what is used a key. The key is the namespace for which it is registered, and so it depends of what is used in the code you want to load.

**Comment by leevigraham** [comment]
I'll move it to the manager.
